apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    service: db
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
  labels:
    account: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      version: v1
  template:
    metadata:
      labels:
        app: db
        version: v1
    spec:
      serviceAccountName: db
      containers:
      - name: db
        image: 086296749009.dkr.ecr.eu-west-2.amazonaws.com/db
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
